### ISSUE TITLE
LINEのアプリのようにアプリのサムネイルのところにチャットの数を出す

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-ios#5]
![screenshot_20170504-234136](https://cloud.githubusercontent.com/assets/17405609/25709145/7ff4f332-3123-11e7-841c-3446f5a9026b.png)

このちゃぽーとのボタンに数字を出してください。
iphone,android兼用

**Comment by alexeypolitov** [comment]
@tomoyuki1110 修正しました。アプリは審査を取れたらご確認できるようになります。

**Comment by take-iwa** [comment]
@alexeypolitov iOSの方はバッジ表示されます。OKです。
![img_0009 2](https://user-images.githubusercontent.com/23730555/28522045-67950fc0-70b1-11e7-9679-c5689f1f29ba.PNG)

andoroid版ってバッジの表示ありましたっけ？

**Comment by tomoyuki1110** [comment]
アンドロイドはバッチ表示されてないですね

**Comment by tomoyuki1110** [comment]
Androidもバッチ表示できるようにお願い致します
