### ISSUE TITLE
接続できない

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-ios#7]
@alexeypolitov  すみません。
久々にchapportのiOSアプリでチャット使おうとしたら、“Socket is not connected.“と出ます。
(なぜが通知は届いてます)

また、Androidだとipass合っているはずなのに、"User not find"ログインすらできず。

httpsの影響？
確認願います。

**Comment by alexeypolitov** [comment]
@take-iwa どっちも修正しました。androidはアップデートの形でご確認可能です。iosはtestflightでダウンロードしていただいてご確認ください。iosについて審査下りたらapp storeでもご確認可能となります
